name: AdvancedAntiCheatPaper
main: com.example.anticheat.AdvancedAntiCheatPaper
version: 1.0.0
api-version: 1.16
authors: [YourName]
permissions:
  advancedanticheat.bypass:
    description: Bypass anti-cheat
    default: op

